# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NoteBook' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'CocoaAsyncSocket', '~> 7.5.0'
  # Pods for NoteBook

  target 'NoteBookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NoteBookUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
