# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'NoteBook' do
    
  pod 'CocoaAsyncSocket', '~> 7.5.0'
  
  
  target 'NoteBookTests' do
    inherit! :search_paths
  end

  target 'NoteBookUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
